export enum ErrorContext {
  LOGIN_ERROR = 'LOGIN_ERROR'
}

export enum ErrorType {
  APPLICATION_PENDING = 'APPLICATION_PENDING',
  APPLICATION_REJECTED = 'APPLICATION_REJECTED',
  EVENT_FINISHED = 'EVENT_FINISHED',
  EVENT_HASNT_STARTED = 'EVENT_HASNT_STARTED',
  NOT_MEMBER = 'NOT_MEMBER',
  USER_NOT_FOUND = 'USER_NOT_FOUND'
}
