// ## GRAPHQL EVENTS - Shared between Front-End and Back-End.

export enum MutationEvent {
  APPLY_TO_COMMUNITY = 'applyToCommunity',
  CREATE_COMMUNITY = 'createCommunity',
  CREATE_EVENT = 'createEvent',
  CREATE_EVENT_ATTENDEE = 'createEventAttendee',
  CREATE_EVENT_GUEST = 'createEventGuest',
  CREATE_EVENT_WATCH = 'createEventWatch',
  CREATE_LIFETIME_PAYMENT = 'createLifetimePayment',
  CREATE_MEMBER_PLANS = 'createMemberPlans',
  CREATE_SUBSCRIPTION = 'createSubscription',
  DELETE_EVENT = 'deleteEvent',
  DELETE_EVENT_GUEST = 'deleteEventGuest',
  DELETE_MEMBERS = 'deleteMembers',
  DEMOTE_MEMBERS = 'demoteMembers',
  INVITE_MEMBERS = 'inviteMembers',
  LOGOUT = 'logout',
  PROMOTE_MEMBERS = 'promoteMembers',
  REMOVE_STRIPE_SUBSCRIPTION_ID = 'removeStripeSubscriptionId',
  RESPOND_TO_APPLICANTS = 'respondToApplicants',
  RESTORE_MEMBERS = 'restoreMembers',
  SEND_LOGIN_LINK = 'sendLoginLink',
  UPDATE_EVENT = 'updateEvent',
  UPDATE_MAILCHIMP_LIST_ID = 'updateMailchimpListId',
  UPDATE_MEMBER = 'updateMember',
  UPDATE_MEMBER_SOCIALS = 'updateMemberSocials',
  UPDATE_MEMBER_VALUES = 'updateMemberValues',
  UPDATE_QUESTION = 'updateQuestion',
  UPDATE_RECORDING_URL = 'updateRecordingUrl',
  UPDATE_STRIPE_PAYMENT_METHOD_ID = 'updateStripePaymentMethodId',
  VERIFY_TOKEN = 'verifyToken'
}

export enum QueryEvent {
  GET_ACTIVE_MEMBERS_GROWTH = 'getActiveMembersGrowth',
  GET_ACTIVE_MEMBERS_SERIES = 'getActiveMembersSeries',
  GET_APPLICANTS = 'getApplicants',
  GET_APPLICATION = 'getApplication',
  GET_CHANGE_PREVIEW = 'getChangePreview',
  GET_COMMUNITY = 'getCommunity',
  GET_COMMUNITY_INTEGRATIONS = 'getCommunityIntegrations',
  GET_COMMUNITIES = 'getCommunities',
  GET_EVENT = 'getEvent',
  GET_EVENT_ATTENDEES = 'getEventAttendees',
  GET_EVENT_ATTENDEES_SERIES = 'getEventAttendeesSeries',
  GET_EVENT_GUESTS = 'getEventGuests',
  GET_EVENT_WATCHES = 'getEventWatches',
  GET_MEMBER_INTEGRATIONS = 'getMemberIntegrations',
  GET_MEMBER_PLANS = 'getMemberPlans',
  GET_MEMBER_SOCIALS = 'getMemberSocials',
  GET_MEMBER_VALUES = 'getMemberValues',
  GET_MEMBER = 'getMember',
  GET_MEMBERS = 'getMembers',
  GET_MEMBERS_GROWTH = 'getMembersGrowth',
  GET_MEMBERS_SERIES = 'getMembersSeries',
  GET_OWNER = 'getOwner',
  GET_PAST_EVENTS = 'getPastEvents',
  GET_PAYMENTS = 'getPayments',
  GET_PAYMENTS_SERIES = 'getPaymentsSeries',
  GET_RANKED_QUESTIONS = 'getRankedQuestions',
  GET_QUESTIONS = 'getQuestions',
  GET_TOKENS = 'getTokens',
  GET_UPCOMING_EVENTS = 'getUpcomingEvents',
  GET_UPCOMING_EVENT_GUESTS = 'getUpcomingEventGuests',
  GET_USER = 'getUser',
  IS_EMAIL_TAKEN = 'isEmailTaken'
}
