import day from 'dayjs';
import React from 'react';

import Button from '@atoms/Button/Button';
import { ModalType } from '@constants';
import Card from '@containers/Card/Card';
import Row from '@containers/Row/Row';
import QuestionBox from '@molecules/QuestionBox/QuestionBox';
import { QuestionBoxItemProps } from '@molecules/QuestionBox/QuestionBox.types';
import {
  IMember,
  IMemberData,
  IQuestion,
  IUser,
  MemberStatus
} from '@store/Db/entities';
import IdStore from '@store/Id.store';
import { useStoreActions, useStoreState } from '@store/Store';
import ApplicantsRespondButton from './ApplicantsRespondButton';

const ApplicantsCardHeader: React.FC = () => {
  const showModal = useStoreActions(({ modal }) => modal.showModal);
  const memberId: string = IdStore.useStoreState(({ id }) => id);

  const createdAt: string = useStoreState(({ db }) => {
    const member: IMember = db.byMemberId[memberId];
    return day(member?.createdAt).format('M/D/YY');
  });

  const fullName: string = useStoreState(({ db }) => {
    const member: IMember = db.byMemberId[memberId];
    const user: IUser = db.byUserId[member?.user];
    return `${user?.firstName} ${user?.lastName}`;
  });

  const onClick = () => {
    showModal({ id: ModalType.APPLICANT, metadata: memberId });
  };

  return (
    <Row className="mb-md" justify="sb" spacing="xs">
      <div>
        <p className="meta">Applied {createdAt}</p>
        <h3>{fullName}</h3>
      </div>

      <Button tertiary onClick={onClick}>
        See Full Application
      </Button>
    </Row>
  );
};

const ApplicantsCardActionContainer: React.FC = () => {
  const memberId: string = IdStore.useStoreState(({ id }) => id);

  return (
    <Row equal className="mt-auto" spacing="xs">
      <ApplicantsRespondButton
        applicantIds={[memberId]}
        response={MemberStatus.ACCEPTED}
      />

      <ApplicantsRespondButton
        applicantIds={[memberId]}
        response={MemberStatus.REJECTED}
      />
    </Row>
  );
};

const ApplicantsCardItems: React.FC = () => {
  const memberId: string = IdStore.useStoreState(({ id }) => id);

  const items: QuestionBoxItemProps[] = useStoreState(({ db }) => {
    const member: IMember = db.byMemberId[memberId];

    const data: IMemberData[] = member.data?.map(
      (dataId: string) => db.byDataId[dataId]
    );

    return db.community.questions
      ?.map((questionId: string) => db.byQuestionId[questionId])
      ?.filter((question: IQuestion) => {
        return !question?.autoGenerated && !question?.category;
      })
      ?.map((question: IQuestion) => {
        const element: IMemberData = data?.find((entity: IMemberData) => {
          return entity.question === question.id;
        });

        return {
          title: question?.title,
          type: question?.type,
          value: element?.value
        };
      })
      ?.slice(0, 5);
  });

  return <QuestionBox className="mb-md" items={items} />;
};

const ApplicantsCard: React.FC = () => {
  return (
    <Card>
      <ApplicantsCardHeader />
      <ApplicantsCardItems />
      <ApplicantsCardActionContainer />
    </Card>
  );
};

export default ApplicantsCard;
