export enum ModalType {
  ADD_MEMBER = 'ADD_MEMBER',
  CHECK_IN = 'CHECK_IN',
  CONFIRM_APPLICANTS = 'CONFIRM_APPLICANTS',
  CONFIRM_DELETE_EVENT = 'CONFIRM_DELETE_EVENT',
  CONFIRM_RSVP = 'CONFIRM_RSVP',
  CREATE_EVENT = 'CREATE_EVENT',
  DELETE_ADMINS = 'DELETE_ADMINS',
  DELETE_MEMBERS = 'DELETE_MEMBERS',
  DEMOTE_MEMBERS = 'DEMOTE_MEMBERS',
  PROMOTE_MEMBERS = 'PROMOTE_MEMBERS',
  UPDATE_EVENT = 'UPDATE_EVENT',
  UPDATE_MEMBERSHIP_INFORMATION = 'UPDATE_MEMBERSHIP_INFORMATION',
  UPDATE_PERSONAL_INFORMATION = 'UPDATE_PERSONAL_INFORMATION',
  UPDATE_SOCIAL_INFORMATION = 'UPDATE_SOCIAL_INFORMATION',
  VIEW_APPLICANT = 'VIEW_APPLICANT',
  VIEW_EVENT_ERROR = 'VIEW_EVENT_ERROR',
  VIEW_PROFILE = 'VIEW_PROFILE'
}

export interface ModalState {
  id: ModalType;
  lock?: boolean;
  metadata?: unknown;
}
