import React from 'react';

import Row from '@containers/Row/Row';
import { IQuestion } from '@store/Db/entities';
import { useStoreState } from '@store/Store';
import ListFilterQuestion from '../ListFilterQuestion/ListFilterQuestion';
import ListFilterActions from './ListFilterActions';
import ListFilterClearButton from './ListFilterClearButton';

const ListFilterHeader: React.FC = () => {
  return (
    <Row className="mx-xs my-sm" justify="sb">
      <h3>Filters</h3>
      <ListFilterClearButton />
    </Row>
  );
};

const ListFilterQuestionList: React.FC = () => {
  const questions: IQuestion[] = useStoreState(({ db }) => {
    return db.community.questions
      ?.map((questionId: string) => db.byQuestionId[questionId])
      ?.filter((question: IQuestion) => {
        return !question.autoGenerated && !!question.options?.length;
      });
  });

  return (
    <ul className="mb-sm">
      {questions?.map(({ id }: IQuestion) => {
        return <ListFilterQuestion key={id} id={id} />;
      })}
    </ul>
  );
};

const ListFilter: React.FC = () => {
  return (
    <>
      <ListFilterHeader />
      <ListFilterQuestionList />
      <ListFilterActions />
    </>
  );
};

export default ListFilter;
