import React, { useEffect } from 'react';

import Row from '@containers/Row/Row';
import { IQuestion } from '@store/Db/entities';
import { useStoreState } from '@store/Store';
import PanelCloseButton from '../../Panel/PanelCloseButton';
import ListFilterQuestion from '../ListFilterQuestion/ListFilterQuestion';
import ListFilterStore from './ListFilter.store';
import ListFilterApplyButton from './ListFilterApplyButton';
import ListFilterClearButton from './ListFilterClearButton';

const ListFilterHeader: React.FC = () => {
  return (
    <Row className="mx-xs my-sm" justify="sb">
      <h3>Filters</h3>
      <ListFilterClearButton />
    </Row>
  );
};

const ListFilterQuestionList: React.FC = () => {
  const questions: IQuestion[] = useStoreState(({ db }) => {
    return db.community.questions
      ?.map((questionId: string) => db.byQuestionId[questionId])
      ?.filter((question: IQuestion) => {
        return !question.autoGenerated && !!question.options?.length;
      });
  });

  return (
    <ul className="mb-sm">
      {questions?.map(({ id }: IQuestion) => {
        return <ListFilterQuestion key={id} id={id} />;
      })}
    </ul>
  );
};

const ListFilterActions: React.FC = () => {
  return (
    <Row className="mx-xs my-sm">
      <ListFilterApplyButton />
      <PanelCloseButton />
    </Row>
  );
};

const ListFilter: React.FC = () => {
  const setOpenQuestionId = ListFilterStore.useStoreActions(
    (state) => state.setOpenQuestionId
  );

  // When the panel closes, ensure that no question is expanded when it opens
  // back up again.
  useEffect(() => {
    return () => setOpenQuestionId(null);
  }, []);

  return (
    <>
      <ListFilterHeader />
      <ListFilterQuestionList />
      <ListFilterActions />
    </>
  );
};

export default ListFilter;
